#autogen.py

genScript = open("genScript.txt", "wb")

genScript.write("RECOVER m-0\n")
genScript.write("SLEEP 2000\n")
genScript.write("RECOVER m-1\n")
genScript.write("SLEEP 2000\n")
genScript.write("RECOVER m-2\n")
genScript.write("SLEEP 2000\n")
genScript.write("UNFREEZE d-0\n")
genScript.write("SLEEP 2000\n")
genScript.write("UNFREEZE d-1\n")
genScript.write("SLEEP 2000\n")
genScript.write("UNFREEZE d-2\n")
genScript.write("SLEEP 2000\n")
genScript.write("UNFREEZE d-3\n")
genScript.write("SLEEP 2000\n")
genScript.write("UNFREEZE d-4\n")
genScript.write("SLEEP 2000\n")
genScript.write("UNFREEZE d-5\n")
genScript.write("SLEEP 2000\n")
genScript.write("UNFREEZE d-6\n")
genScript.write("SLEEP 2000\n")
genScript.write("UNFREEZE d-7\n")
genScript.write("SLEEP 2000\n")
genScript.write("UNFREEZE d-8\n")
genScript.write("SLEEP 2000\n")
genScript.write("UNFREEZE d-9\n")
genScript.write("SLEEP 4000\n")

#"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
#\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\"\n
for i in range(10):
  genScript.write("CREATE c-"+str(i)+" A"+str(i)+" 3 3 3\n")
  genScript.write("SLEEP 3000\n")
  genScript.write("CREATE c-"+str(i)+" B"+str(i)+" 3 3 3\n")
  genScript.write("CREATE c-"+str(i)+" C"+str(i)+" 3 3 3\n")
  genScript.write("CREATE c-"+str(i)+" D"+str(i)+" 3 3 3\n")
  genScript.write("CREATE c-"+str(i)+" E"+str(i)+" 3 3 3\n")
  genScript.write("CREATE c-"+str(i)+" F"+str(i)+" 3 3 3\n")
  genScript.write("CREATE c-"+str(i)+" G"+str(i)+" 3 3 3\n")
  genScript.write("CREATE c-"+str(i)+" H"+str(i)+" 3 3 3\n")
  genScript.write("CREATE c-"+str(i)+" I"+str(i)+" 3 3 3\n")
  genScript.write("CREATE c-"+str(i)+" J"+str(i)+" 3 3 3\n")
  genScript.write("SLEEP 4000\n")
  genScript.write("WRITE c-"+str(i)+" 0 \"BANANA\"\n")
  genScript.write("WRITE c-"+str(i)+" 1 \"MORANGO\"\n")
  genScript.write("WRITE c-"+str(i)+" 2 \"ABACAXI\"\n")
  genScript.write("WRITE c-"+str(i)+" 3 \"PERA\"\n")
  genScript.write("WRITE c-"+str(i)+" 4 \"MELOA\"\n")
  genScript.write("WRITE c-"+str(i)+" 5 \"LARANJA\"\n")
  genScript.write("WRITE c-"+str(i)+" 6 \"MELANCIA\"\n")
  genScript.write("WRITE c-"+str(i)+" 7 \"MACA\"\n")
  genScript.write("WRITE c-"+str(i)+" 8 \"ARROZDOCE\"\n")
  genScript.write("WRITE c-"+str(i)+" 9 \"LEITECREME\"\n")
  genScript.write("SLEEP 4000\n")
  genScript.write("CLOSE c-"+str(i)+" A"+str(i)+"\n")
  genScript.write("CLOSE c-"+str(i)+" B"+str(i)+"\n")
  genScript.write("CLOSE c-"+str(i)+" C"+str(i)+"\n")
  genScript.write("CLOSE c-"+str(i)+" D"+str(i)+"\n")
  genScript.write("CLOSE c-"+str(i)+" E"+str(i)+"\n")
  genScript.write("CLOSE c-"+str(i)+" F"+str(i)+"\n")
  genScript.write("CLOSE c-"+str(i)+" G"+str(i)+"\n")
  genScript.write("CLOSE c-"+str(i)+" H"+str(i)+"\n")
  genScript.write("CLOSE c-"+str(i)+" I"+str(i)+"\n")
  genScript.write("CLOSE c-"+str(i)+" J"+str(i)+"\n")
  genScript.write("SLEEP 4000\n")

   
genScript.write("DUMP m-0\n")
genScript.write("SLEEP 4000\n")
genScript.write("LOADBALANCE m-0\n")
genScript.close()